# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function perform Frechet regression with the Wasserstein distance.
#'
#' @param xfit A nxp matrix of predictor values for fitting (do not include a column for the intercept).
#' @param q A nxm matrix of quantile density functions. q(i, :) is a 1xm vector of quantile density function values on an equispaced grid on [0, 1].
#' @param Q0 A 1xn array of quantile function values at 0.
#' @param xpred A kxp matrix of input values for regressors for prediction.
#' @param t A 1xm vector - common grid for all quantile density functions in q.  If missing, defaults to linspace(0, 1, m);  For best results, should use a finer grid than for quantle estimation, especially near the boundaries.
#' @param qdmin A positive lower bound on the estimated quantile densites. Defaults to 1e-6.
#'
#' @return An object containing the components:
#' \code{xpred} See input of same name.
#' \code{qpred} A kxN array.  qpred(l,:) is the regression prediction of q (the quantile density) given X = xpred(l, :)'
#' \code{Qpred} A kxm array. Qpred(l, :) is the regression prediction of Q given X = xpred(l, :)'
#' \code{fpred} A kxm array. fpred(l, :) is the regression prediction of f (the density) given X = xpred(l, :)', evaluated on the grid Qpred(l, :)
#' \code{xfit} See input of same name.
#' \code{qfit} A nxN array. qfit(l, :) is the regression prediction of q given X = xfit(l, :)'
#' \code{Qfit} A nxm array. Qfit(l, :) is the regression prediction of Q given X = xfit(l, :)'
#' \code{fpred} A kxm array. fpred(l, :) is the regression prediction of f (the density) given X = xpred(l, :)', evaluated on the grid Qfit(l, :)
#' \code{QP_used} A flag indicating whether OLS fits all satisfied the constraints (=0) or if the quadratic program was used in fitting (=1).
cpp_wasserstein_regression <- function(xfit, q, Q0, xpred, t, qdmin) {
    .Call(`_biosensors_usc_cpp_wasserstein_regression`, xfit, q, Q0, xpred, t, qdmin)
}

#' This function computes intrinsic confidence bands for Wasserstein regression.
#'
#' @param xfit A nxp matrix of predictor values for fitting (do not include a column for the intercept).
#' @param xpred A kxp matrix of input values for regressors for prediction.
#' @param Q_obs A nxm matrix of quantile functions. Q_obs(i, :) is a 1xm vector of quantile function values on grid t_vec.
#' @param q_obs A nxm matrix of quantile density functions. q_obs(i, :) is a 1xm vector of quantile density function values on grid t_vec.
#' @param t_vec A 1xm vector - common grid for all quantile density functions in Q_obs, q_obs, q_prime_obs.
#' @param alpha The significant level is 100*(1 - alpha).
#'
#' @return An object containing the components:
#' \code{Q_lx} Lower bound of confidence bands in terms of density functions.
#' \code{Q_ux} Upper bound of confidence bands in terms of density functions.
#' \code{Qpred} Fitted density function at xpred.
cpp_confidence_band <- function(xfit, xpred, Q_obs, q_obs, t_vec, alpha) {
    .Call(`_biosensors_usc_cpp_confidence_band`, xfit, xpred, Q_obs, q_obs, t_vec, alpha)
}

cpp_nadayara_regression <- function(X, t, Y, hs, indices_1, indices_2) {
    .Call(`_biosensors_usc_cpp_nadayara_regression`, X, t, Y, hs, indices_1, indices_2)
}

cpp_nadayara_prediction <- function(X, t, Y, hs, indices_1, indices_2) {
    .Call(`_biosensors_usc_cpp_nadayara_prediction`, X, t, Y, hs, indices_1, indices_2)
}

cpp_ridge_regression <- function(dist, Y, W, w, lambdas, sigmas) {
    .Call(`_biosensors_usc_cpp_ridge_regression`, dist, Y, W, w, lambdas, sigmas)
}

