# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_nadayara_regression <- function(X, t, Y, hs, indices_1, indices_2) {
    .Call(`_biosensors_usc_cpp_nadayara_regression`, X, t, Y, hs, indices_1, indices_2)
}

cpp_nadayara_prediction <- function(X, t, Y, hs, indices_1, indices_2) {
    .Call(`_biosensors_usc_cpp_nadayara_prediction`, X, t, Y, hs, indices_1, indices_2)
}

cpp_ridge_regression <- function(dist, Y, W, w, lambdas, sigmas) {
    .Call(`_biosensors_usc_cpp_ridge_regression`, dist, Y, W, w, lambdas, sigmas)
}

